import { Brewery } from '../types/brewery';

export const mockBreweries: Brewery[] = [
  {
    id: '1',
    name: 'Test Brewery 1',
    brewery_type: 'micro',
    street: '123 Main St',
    address_1: null,
    address_2: null,
    address_3: null,
    city: 'Portland',
    state: 'Oregon',
    county_province: null,
    postal_code: '97201',
    country: 'United States',
    longitude: '-122.6765',
    latitude: '45.5152',
    phone: '503-555-0100',
    website_url: 'https://testbrewery1.com',
    state_province: null,
  },
  {
    id: '2',
    name: 'Another Brewery',
    brewery_type: 'brewpub',
    street: '456 Oak Ave',
    address_1: null,
    address_2: null,
    address_3: null,
    city: 'Seattle',
    state: 'Washington',
    county_province: null,
    postal_code: '98101',
    country: 'United States',
    longitude: '-122.3321',
    latitude: '47.6062',
    phone: '206-555-0200',
    website_url: null,
    state_province: null,
  },
  {
    id: '3',
    name: 'Zebra Brewing',
    brewery_type: 'regional',
    street: null,
    address_1: '789 Pine St',
    address_2: null,
    address_3: null,
    city: 'Denver',
    state: 'Colorado',
    county_province: null,
    postal_code: '80202',
    country: 'United States',
    longitude: null,
    latitude: null,
    phone: null,
    website_url: 'https://zebrabrewing.com',
    state_province: null,
  },
];

export const mockFilters = {
  name: '',
  type: '',
  city: '',
  state: '',
};
